### ISSUE TITLE
Wishlist: Select field with search

### ISSUE THREAD

**Issue by turban** [dhis2/ui-core#133]
Would it be possible to have a select field with search and windowing? Sometimes a select can have hundreds and even thousands of options. 

Example: Diagnosis (ICD-10) option set with 14240 options! 

Sketch from Joe: 

![screen shot 2019-01-18 at 15 49 35](https://user-images.githubusercontent.com/548708/51394138-e88ab100-1b39-11e9-918f-42a87702de07.png)

**Comment by varl** [comment]
We can do filtering on the client.

**Comment by cooper-joe** [comment]
I've had some conversations with @varl about how we might achieve this functionality with a native component. Here is an example of how I believe this could work, in theory (and if I've understood Viktor correctly):
![Searchable select](https://user-images.githubusercontent.com/33054985/57838617-55027d80-77c5-11e9-94e8-7f1e923bacff.png)

In this example we ~~abuse~~ use the native select and filter the available options on every keypress inside the field. We can add help for the user by detecting if there are no results and showing a disabled option to inform them of this. 'None' must always be present as a option, otherwise deselecting is impossible. I'm unsure if we would need to disable the 'type to select' default behaviour of a select field.

I'm interested in hearing views on this, if the slightly unconventional use of a native select is worth it for the benefits here, or if we should go custom.

**Comment by amcgee** [comment]
I understand the desire to stick with native, but I think users will prefer a cleaner, more modern UI.  There also might be some challenges with lazy-loading items from the server, which *may* be useful at some point.

That being said, given the native element constraint I think this would be a really cool solution!

**Comment by Mohammer5** [comment]
> Here is an example of how I believe this could work

@cooper-joe @varl I think it's impossible to have focus on both an input and select element at the same time, which would make this solution impossible.

> I understand the desire to stick with native, but I think users will prefer a cleaner, more modern UI.

@amcgee I don't agree with that. From my experience users don't really care about the UI as long as they understand how things work easily and they get want they want without a hassle (which is why amazon looks quite crap compared to other online stores but is still successful with it, the UX is incredible).
Also the `select` is a special case here. Many users are used to use the native select as it's the default choice by many websites/web apps due to the rich feature set it provides out of the box.

@cooper-joe I understand the need to have this component. Maybe it's a misconception on our side, we think it's a `select` element with a search feature. What if we say it's not a select, but a searchable list, which has a very limited feature set (search, click to select (multiple?), scrollable list), so it can look different from our `select` component.

**Comment by cooper-joe** [comment]
In my experience it is quite rare that a user knows the difference between what is native vs. custom. The only consideration is that it works quickly and without effort. Following that logic, if a user has to select an ICD-10 value from 14,000+ using a native select, they're not going to be satisfied because it's going to require effort. Perhaps as @Mohammer5 started doing, it is worth listing the requirements for this component before we decide on its implementation.

Base requirements: 
- select value from a list of 1 - 15,000+ possible options
- search for a value in the list
- receive feedback if no values match search term
- keyboard control
I would also add the following requirements that I see being useful in the near future:
- multiple selection
- lazy loading of values

Based on those requirements, how does a native `select` or `datalist` fit? My impression is that it doesn't. Perhaps this an argument for having two types of select in `ui-core`. Basic, which uses native controls, and Advanced, which fulfills all criteria listed above using a completely custom solution. Keeping these components seperate, as they solve seperate user needs, may be the right direction.

**Comment by HendrikThePendric** [comment]
I like something like the Twitter TypeAhead UI. Don't make this look like a select, because it isn't. The [default example](https://twitter.github.io/typeahead.js/) illustrates how I would like things to work for single-select.

For multi-select I still like the TypeAhead, but then I would like to combine it with deletable chips, [like in this code-pen](https://codepen.io/mohbasheer/pen/JXKLyY).

Downside of the TypeAhead is that you don't see anything until you start typing. Alternatively, I quite like something like [this Vue multi-select component](https://vue-multiselect.js.org/) (But I really do prefer the TypeAhead)
