### ISSUE TITLE
Generic class names are causing global styles to be applied in some cases

### ISSUE THREAD

**Issue by jenniferarnesen** [dhis2/ui-core#213]
Specific case: disabled Menu item
The disabled menu item has class `disabled`. This results in some global styles being applied. The global styles are coming from some old analytics plugins (used for generating pivot tables event reports, etc). We are hesitant to change these old plugins and wonder if ui-core can take a different approach to avoid having generic classnames. Here is a screenshot of some applied styles:

![image](https://user-images.githubusercontent.com/6113918/57611185-8df6e400-7572-11e9-8e8a-fbd178dbd3f8.png)

**Comment by varl** [comment]
@jenniferarnesen Use of `!important` is a serious offense from the plugins, and might lead to other problems in the App. Is there no way to at least fix that part?

`opacity` will still leak in, but at least it softens it a bit so it could be overridden.

**Comment by jenniferarnesen** [comment]
Well, we could look into it, but it has been there for a long time and I'm not sure how much work it would be to pull it out. Would involve a fair amount of testing in our old, stable apps.

**Comment by varl** [comment]
### Solution

The best practice is for the App to isolates its CSS to its own components. This can be done using inline styles, `styled-components`, `styled-jsx`, or some other chosen CSS-in-JS solution. They all pretty much enable this out of the box.

If the App components do not leak their styles then none of the `ui-core` components will be affected. `ui-core` currently gives the guarantee that it will not leak its styles, and I think it's fair to assume that other components will not allow their styles to leak either.

### Problem with trying to solve this in the `ui-core` library

The problem here is that there is a global stylesheet added to the App which leaks to every single component on the page, so the problem is not easily solved in `ui-core`.

Even if we change our internal classes from `.disabled` to a prefixed `.ui-disabled`, the problem will reappear if there is a global `.ui-disabled` class.

If we change to only target HTML elements, we are still not protected against rules like: `button { background-color: blue !important;`. Those will still leak into our components.

### Workaround

If the global styles in the App cannot be controlled, then the App must also define a "reset" class which is passed to the component through the `className` prop, e.g.:

**App global style:**

```
.disabled {
    opacity: 0.4 !important;
    background-color: blue !important;
}
```

**App reset style:**

```
.disabled-fix {
    opacity: 1.0 !important;
    background-color: red !important;
}
```

**App component usage:**

```
<Button className="disabled-fix" disable>Overriden button</Button>
```
