### ISSUE TITLE
Deselectable radio

### ISSUE THREAD

**Issue by teug91** [dhis2/ui-core#228]
The Radio component does not fire the onChange function when the user clicks a checked radio. This behavior is standard for html radio inputs, [but the info states that it should be deselectable](https://github.com/dhis2/ui-core/blob/master/stories/info/atoms/radio.md):
> A user can deselect a radio button by clicking a selected radio button again.

I'm fine with handling it myself in my apps, but thought you should know. :+1:

**Comment by Mohammer5** [comment]
@varl I tend to stick with the standard behavior.

But as this is a controlled component, simply changing `onChange` to `onClick` should do the trick. The app would have to implement changing the value to false though as `event.target.value` will always be `true`.

**Comment by varl** [comment]
Interesting, I missed that part of the spec.

**Comment by cooper-joe** [comment]
After discussion, conclusion is reached:
- Do not add deselect functionality to radio buttons in ui-core
because:
- it breaks the spec
- it is spreading ‘bad habits’
- tracker capture (where this is the biggest issue) is currently undergoing a full redesign, so ‘toggles’ can be added in, or radio buttons can be switched out for more appropriate controls for these input types

I think we can revisit this issue if/when this problem is found in other places, but I think, on reflection and discussion, it would be a bad idea to encourage misuse of the component by building in the functionality

Design specs updated to reflect this.
