### ISSUE TITLE
Decorate propType definitions with comments to populate the prop-table description fields

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui-core#413]
I really like the prop-tables that are generated by [storybook-addon-react-docgen](https://github.com/hipstersmoothie/storybook-addon-react-docgen). However, I feel like some props would really benefit from having some more info included in the "description" column of the prop-table...

This works out of the box when using jsDoc-like comment-syntax, i.e.
```javascript
BestComponentEvah.propTypes = {
    sarcasmMode: propTypes.bool,
    /**
     * When set to true, quotes will appear around the text to emphasise that we don't really mean it.
     */
}
```
The above comment will now be inserted into the description column of the prop-table.

So now all that is left to do is "just" review all components and add descriptions to props that need it...
(sarcasm mode was on when I wrote that)

**Comment by varl** [comment]
Agreed that we need descriptions, but we should go about it in a different way.

When adding user documentation in the branch `docs/docs` I ran into the situation where I would have to duplicate the docstrings for jsdoc and docgen, I opted for prioritizing jsdoc for consistency with our other documentation, and the full API docs is more important than the props table in Storybook.

While it is possible to turn Storybook into some form of user documentation, I think that Storybook shines when used in development; as a API/usage documentation tool it is bloated, slow, and hard to cenralise since it doesn't generate e.g. markdown output.

E.g. the button propTypes docstring looks like: https://github.com/dhis2/ui-core/blob/docs/docs/src/Button.js#L75-L98

Rendered result: https://deploy-preview-397--dhis2-ui-core.netlify.com/#/api?id=button-%e2%87%92-reactcomponent

Take a look at #397 for the entire thing.

**Comment by HendrikThePendric** [comment]
> I opted for prioritizing jsdoc for consistency with our other documentation, and the full API docs is more important than the props table in Storybook.

Makes perfect sense and docs are looking very good. Sorry I wasn't aware you were working on this already. I'll close this one.
