### ISSUE TITLE
Where to put default translated texts?

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui-core#794]
## Intro
We decided a long time ago that `ui-core` should not use `@dhis2/i18n`. Everyone was on board with that decision but it turns out the situation that landed us in is far from ideal. We either need to find a better solution for adding translated default texts, or reconsider putting i18n into `ui-core`.

## Current approach
Currently we have identified three components in `ui-core` that need a quite a few translated default/placeholder texts:
- `SingleSelect`
- `MultiSelect`
- `FileInputFieldWithList`

The approach we tried was to export counter-parts for these components from `ui-widgets` that do contain translations. See https://github.com/dhis2/ui-widgets/pull/309 for more info.

### Problems
As I see it, the main problem with this approach is that it makes the distinction between `ui-widgets` and `ui-core` very blurry. My current metal model is like this:
> ui-core has component-primitives and ui-widgets has components that interact with the dhis2-core webapi, or contain business logic.

That distinction has proved to be fairly hard to grasp, but with the `i18n` we'll need to add another criteria to that distinction:
> [...] or contain translations

A new developer in the ecosystem can't really be expected to know he/she should work like this when wanting to use a `MultiSelect` with the default translations:
```javascript
import { MultiSelectField } from '@dhis2/ui-widgets'
import { MultiSelectOption } from '@dhis2/ui-core'
```

There are some other factors that make the current approach problematic, but I think we should only focus on the one above, because this relates directly to our "end-product".

## Alternative approaches
I've already started discussing this on Slack with @ismay and @Mohammer5 and some alternatives were suggested:

### A library with translated components
Probably this would just re-export all ui-core components but just add translated defaultProps. Personally I wouldn't like this.

### A translation library / a translations helper in an existing library
There are many ways we could implement something like this:
1. Just exporting the translated text as a const and apply it to each individual prop (explicit, but not very convenient)
2. A HoC (might be interesting, but will create an additional component-layer)
3. A helper that just appends the relevant defaultProps to the components that need it (could be convenient, but probably quite quirky)

### Adding `@dhis2/i18n` to `ui-core`
Yes.... I know.... We weren't going to do that... But the other solutions all seem a bit off as well....

**Comment by amcgee** [comment]
I think I'd be in favor of adding translations to `ui-core` for consistency and to keep it self-contained (otherwise you basically duplicate the "helper text" and all its translations everywhere it's used).

I think this could/should be done cleanly with a Context-based i18n approach which we're hoping to implement, rather than the singleton-based `@dhis2/d2-i18n` we currently use.

**Comment by ismay** [comment]
I think either adding translations to ui-core, or having a separate translations lib would have my preference. I agree with @HendrikThePendric that adding translated ui-core components to ui-widgets would muddy the scope of ui-widgets.

**Comment by Mohammer5** [comment]
I think I'm in favor of adding it as well.
We could even think about a more sophisticated way with dynamic imports and props to control what should be translated if we want to go down that path.

<hr />

If we end the end decide against it, my preference would be a translation library that provides a function, which will returns an object with the translated prop.

Here's an example how that could look like:

```js
import { MultiSelect } form '@dhis2/ui-core`
import { getTranslatedProps } from '@dhis2/ui-translation'

const multiSelectTranslations = getTranslatedProps(MultiSelect)
/**
 * Assuming we're using react-final-form
 */

// If we want all translations
<Field
  component={MultiSelect}
  {...multiSelectTranslations}
  // ...
/>

// if we want a sub set only
<Field
  component={MultiSelect}
  noMatchText={multiSelectTranslations.noMatchText}
  // ...
/>
```

The reason why I'd prefer this way is:

1. It will support all possible scenarios: `render`/`component` props and regular jsx `children`
1. It allows full control over which translations the app wants to use
1. There's a clear correlation between translations and components (no guesswork which translation should be used if they're not connected to a component)
1. Even if apps use `react-redux`'s `connect` function, this is still usable

**Comment by HendrikThePendric** [comment]
In my mind, adding translations to `ui-core` would be the most elegant solution too. 

---
And similar to @Mohammer5 my second-best approach would be to introduce some helper, which would do something like this:

`addTranslationsTo.js`
```javascript
import i18n from '@dhis2/d2-i18n'

const defaultTexts = {
    MultiSelectField: {
        clearText: i18n.t('Clear'),
        filterPlaceholder: i18n.t('Filter'),
        loadingText: i18n.t('Loading'),
        noMatchText: i18n.t('No Match'),
    }
}

const addTranslationsTo = Component => {
    const key = Component.displayName || Component.name
    Component.defaultProps = {
        ...Component.defaultProps,
        ...defaultTexts[key],
    }
}
export { addTranslationsTo }
```

`MyComponentWithTranslation`
```javascript
import { MultiSelectField } from '@dhis2/ui-core'
import { addTranslationsTo } from '?'

addTranslationsTo(MultiSelectField)

// Proceed as normal
```

Upsides:
- Convenience
- Consistence

Downsides:
- Imperative style
- Could lead to funky edge cases because this will override the component's defaultProps

---

Let's wait for @varl to share his opinion

**Comment by amcgee** [comment]
In the second case, I think a HOC makes sense (`const TranslatedButton = withTranslations(Button)`), but I definitely prefer the first approach if we can make it clean.  

It should at minimum integrate with translation-aware applications but work in translation-unaware apps.  

It would be nice to support dynamic chunking of translations so it doesn't bloat the bundle, but that's part of the larger i18n overhaul and would require some coordination with the application, since libs can't do dynamic imports on their own.

**Comment by amcgee** [comment]
Ref https://jira.dhis2.org/browse/TECH-22, https://jira.dhis2.org/browse/TECH-186

**Comment by HendrikThePendric** [comment]
Thanks Austin.

I'm going to stop work on https://github.com/dhis2/ui-widgets/pull/309 until we have decided how to resolve this. It looks like we might be closing it in favour of introducing i18n in ui-core. But let's wait for @varl

**Comment by varl** [comment]
The distinction between what a core component is and a non-core component is lies at the center of many things, not least what goes where.

The scopes of ui-core and ui-widgets are inverted. The bar to add components to ui-core should be **high**, and the bar to add components to ui-widgets should be **low**. We behave the other way around.

Originally, I want the core to consist of solely atoms -- no molecules and no organisms. The molecules would be formed in apps or in ui-widgets. This keeps the core components very small, simple, and standalone. I still feel that this would be the best way.

We apply atomic design principles, and we best keep those in mind here as well. For example, translations _never_ belong in an Atom, and the best way to enforce this is to provide a boundary as we have done here.

**The reason translations feels off is because all the *Field components actually do not belong in the core library.**

I have had a refactor bouncing around in the back of my head (might have mentioned it to some of you already).

I want to merge all the ui-libs to a monorepo and move around some bits and bobs:

```
ui
├── core
│   ├── package.json
│   └── src
│       ├── Field.js
│       ├── Help.js
│       └── Input.js
├── forms
│   ├── package.json
│   └── src
│       └── InputFieldControl.js
├── layouts
│   ├── package.json
│   └── src
├── ui
│   ├── index.js
│   └── package.json
└── widgets
    ├── package.json
    └── src
        └── InputField.js
```

Note that only the atoms are in the core package, and the Field has move to widgets. There it can contain translations, or whatever else it needs (additional dependencies, etc.).

The other notable thing is the `ui` package -- this would basically re-export and bundle all the ui-libs into a single dependency for consumers.

This discussion and the outcome worries me, so I propose that we consider the option outlined above as a solution to this issue:

1. It allows for boundaries between core components and widgets.
2. The distinction between core and widgets becomes clear (if not, read Atomic Design again).
3. Core components remain entirely prop-driven
4. Added flexibility when using dependencies (laxer in widgets, very strict in core)
5. It allows for translated UI components for molecules

**Comment by Mohammer5** [comment]
@varl In our previous definition of `core` & `widgets`, we said that dhis2 related stuff should go to `widgets` and other things should go to `core` [(Here's our status-quo definition)](https://github.com/dhis2/notes/issues/60#issuecomment-523633029).

#### With your new structure, would you combine all dhis2-related components & all more-than-atom components into widgets?

While simplifying the where-to-put-what question, to me this would introduce confusion again, especially as a consumer of `widgets`. I wouldn't know which component is simply a more-than-an-atom component or a dhis2 specific component (especially as we agreed that not only dhis2-side-effect components should be included in `widgets` but also components that work with dhis2-specific data).

`widgets` would become a multi-purpose library:
1. Molecules, Organisms, etc
2. Components using the DHIS2 api
3. Components using DHIS2 data structure
4. Components having translations (which might be DHIS2 related, or they're purely related to the functionality of that component)

<hr />

#### atomic design

If we're already differentiating between different levels of atomic design in our (inter- & inner-) library structure, I'd prefer if we then use the appropriate names to make things clear. With the `ui` package that bundles all sub-repos, we could do this:

```
ui
│
├── atoms
│   └── src
├── molecules
│   └── src
├── organism
│   └── src
│
├── forms
│   └── src
├── layouts
│   └── src
│
├── widgets # dhis2 related stuff
│   └── src
│
└── ui
    ├── index.js
    └── package.json
```

> It allows for boundaries between core components and widgets

With the above, it'd allow distinction between prop-controlled components (atoms, molecules, organisms). `widgets` would then only be used for adding the DHIS2-layer (turning controlled components into uncontrolled components that use our endpoints, or adding translations, which all could be considered a part of DHIS2-layer)

<hr />

Maybe this discussion goes a bit too deep though, as we might want to talk about the general approach in the first place.. Just wanted to put my opinion on the structure in here as well.

I think it's quite difficult to find a setup that will fulfill all requirements, especially with circular library dependencies (not circular in an endless-loop-way, but more like: `ui-widgets` should translate `ui-forms` (e. g. validators), `ui-forms` should use dhis2-components from `ui-widgets` (e. g. org unit tree), `ui-widgets` builds upon `ui-core`, `ui-forms` uses components from `ui-core` & `ui-widgets`

**Comment by HendrikThePendric** [comment]
> While simplifying the where-to-put-what question, to me this would introduce confusion again, especially as a consumer of `widgets`. I wouldn't know which component is simply a more-than-an-atom component or a dhis2 specific component (especially as we agreed that not only dhis2-side-effect components should be included in `widgets` but also components that work with dhis2-specific data).

But @varl also mentioned the `@dhis2/ui` package, which I think is a great way of preventing the confusion.

In terms of distinction for "us", I think what @varl  proposes could work. The heuristics are fairly simple:
- If it's an atom it goes in ui-core
- if it's bigger, it's a widget

In practice, I think it might sometimes be a bit funky, let's take the Menu for example, I guess the different components for that would be subdivided like so:
- Menu => ui-widgets
- MenuList => ui-core
- MenuListItem => ui-core

it perhaps isn't ideal to have these spread out over two repos, but I guess it does make sense.

In any case, I think we all agree that one of the main contributing factors of what got us here in the first place, is the fact that the scope-definitions of ui-core VS ui-widgets had a gap between them:
- `ui-core` => primitives/atoms
- `ui-widgets` => dhis2 related stuff

_Where would the rest go?_

**Comment by HendrikThePendric** [comment]
I also think that for quite a few/ most of our components, this change would simply mean just copying stuff from one place to the another. The Select stuff could perhaps be an exception.

**Comment by ismay** [comment]
To me the core of the issue seems that the scope of some of our ui libraries is unclear (to us). We keep coming back to discussing what goes where. Apparently `ui-core` and `ui-widgets` leave too much up for interpretation naming wise.

I think as a solution to that I prefer what @Mohammer5 suggests:

```
ui
│
├── atoms
│   └── src
├── molecules
│   └── src
├── organism
│   └── src
├── forms
│   └── src
├── layouts
│   └── src
├── dhis2 # dhis2 related stuff
    └── src
```

By using very explicit names I think we'll prevent confusion about what goes where. We could  further narrow down the exact scope of the libs in the README, but starting with the lib names seems like a good start. So `ui-widgets` becomes `ui/dhis2`, and `ui-core` gets split up in atoms, molecules, etc.

After that we could always decide to bundle them all in a single ui lib, but the above seems like the core issue to me.

**Comment by varl** [comment]
As a note, I consider how _we_ deal with translations a DHIS2-thing, placing it naturally in ui-widgets. 

There are other things to consider as well, like if a user wants to pass in a `placeholder` string to our component, do we attempt to translate that passed in `prop`, or do we then bypass running translations on it? Since we use full sentences as our keys, and we have a match on it, should we translate it?

One thing is clear to me: ui-core should not have translations. It's not part of it's concern, and if we feel we need it in ui-core, that's a symptom of a deeper problem.

**Comment by Mohammer5** [comment]
What about a proper meeting.. There are too many opinions and possible solutions to discuss this in a single github thread. This discussion should also move to `notes`

**Comment by HendrikThePendric** [comment]
Maybe this is a bit controversial... But I actually don't think this is something that requires a meeting. Any distinction works, as long as:
- The criteria to distinguish between ui-core and ui-widgets are understandable and as unambiguous as possible
- There is no overlap in the scope definitions
- There is no gap between the scope definitions

And one remark about ambiguity: the more packages we introduce, the more we'll have to decide "what goes where", and since it's likely that we'll always have to deal with blurry edges to some extend, I'd say we should strive to keep the number of packages down to a minimum. Therefore I don't really like the suggestions that @ismay and @Mohammer5  suggested and prefer the one @varl provided.

**Comment by varl** [comment]
Yeah, I agree @HendrikThePendric. Instead, I will set up a proposal based on what we have discussed here, and then we can have a short meeting to discuss the concrete proposal instead of abstract ideas.

**Comment by Mohammer5** [comment]
Ok, then let me add what my thoughts on the structure above.

### Naming

> The criteria to distinguish between ui-core and ui-widgets are understandable and as unambiguous as possible

I 100% agree to this. But I'd prefer some separation in scope and "proper" names. `core` is very ambiguous, no one will ever know what it means unless you know the definition from somewhere else, which is just bad naming imo.

**So if we want a dedicated place for atoms, we should call it atoms.**

### Splitting `ui-widgets`

The name "`widgets`" is very unclear and actually misleading. What we're trying to achieve is not to have widgets but to have dhis2 related stuff (which could be an organism + api), in the future this might include translations and pure dhis2-unrelated organisms as well. If we want to cover several scopes within one library, it'll become very difficult to find a proper name though, which is why I'd like to take this one apart and create several libraries, at least for our non-dhis2 related components.

As we're already using atomic design to distinguish between different component scopes, I'd say it's easier to understand the scope and component location when creating a `ui/atoms`, `ui/molecules` and `ui/organisms` library.

This would mean that all components that are in `ui-widgets` right now, would have to move to `ui/organisms` and instead of using the data engine directly, expect a callback to do the actual call.

in `ui/dhis2` (which is the name I'd prefer to make clear that everything in here is dhis2 specific), we'd have the HeaderBar and the OrgUnitTree as well, but they're more or less just wrappers with the api callbacks and translations.

### Translations

If we decide to keep translations out of `ui/core` / `ui/atoms`, then I would strongly prefer a utility function rather than a HOC or overwriting default props (which would be a HOC as well if we don't want to mutate the actual component), as that'd give us the most flexibility and would work in all scenarios, even though it's not the most convenient way, it's still fairly convenient (`withTranslations(Component)` vs `<Component {...getTranslationsFor(Component)} />`)

### Conclusion

1. Although that'd result in a bit more work, to me the clear separation of scopes would make it much easier to understand what to expect when looking inside the single libraries.

2, If we let the app consume everything through a `ui` library, the app wouldn't have to think about internal library design

3. As we'd have clear scope already, it'd be pretty easy to extend the scope rather than having a discussion about where to put the next stuff, once we need another library. Otherwise it'll be more or less `ui/core` and `ui/everythingelse`

**Comment by ismay** [comment]
I think we've resolved this now with the translations in ui. Feel free to reopen if I'm wrong.
