### ISSUE TITLE
Only make props required if omitting them will/might cause an error internally

### ISSUE THREAD

**Issue by ismay** [dhis2/ui-core#804]
See here: https://dhis2.slack.com/archives/CBM8LNEQM/p1582043924017500

Quoted from the above link:

> I'm getting console errors for missing labels for the Switch for the scheduler app. However, labels don't make much sense in the area I'm working on:
>
> ![image](https://user-images.githubusercontent.com/7355199/74758597-d8329180-5277-11ea-93d1-85512ab12cee.png)
>
> I can ignore the errors of course, but it makes for a very noisy console
>
> Maybe we shouldn't make a prop required unless omitting it will cause an error in the component's internals. It's tricky to oversee all the usecases, I wouldn't have predicted the above one. But we do know what will internally cause errors. That way we won't spam the console unless it's crucial.

I understand @amcgee had a similar issue. I'd propose we omit `.isRequired` from proptypes _unless_ not passing that prop will break something in the components internals. That's the one thing we can reliably know from within the library I think. Otherwise we'll be cluttering the console with errors that aren't always valid, and people might start ignoring them.

**Comment by HendrikThePendric** [comment]
I think this issue is relevant, but not sure whether I agree with the criteria being proposed:
> we omit .isRequired from proptypes unless not passing that prop will break something in the components internals. 

IMO controlling/signalling intended usage is also a perfectly valid reason for adding `.isRequired`.

And reg. the examples mentioned:
- I think in the case of the `Switch` @ismay encountered, we have now seen a valid use case we were unprepared for.
- For the `RadioGroup` case that @amcgee encountered I am not sure. In v4.0 the `label` prop is only required on the `RadioGroupField`, not on the `RadioGroup` itself. So perhaps this was simply caused by a problem in <4.0 version. Or perhaps the `RadioGroupField` should be swapped for a `RadioGroup`.

Just to clarify, what I am trying to say is the following:
- I think that going through the codebase and reviewing the required props is a useful effort
- But instead of checking "if the component breaks without a given prop", we should **also** be considering if we consider a given prop to be required to the use-cases the component is intended for.

**Comment by varl** [comment]
I do appreciate that it would be great if we could signal how we intend to a component to be used, but the prop types are not the place to do it. We need better user documentation with guides on how to use our components to solve that.

It has already been proven that our "intended use case" does not align with how people want to use our components, so I agree with `isRequired` actually reflects "_this component is going to error and break if you skip this prop_" and not our (good) intentions.

It also makes for a very clear rule when to add `isRequired` vs. when to add better user documentation.

**Comment by HendrikThePendric** [comment]
OK fair enough 👍

**Comment by amcgee** [comment]
One option I thought about for this specific case (if we wanted to explicitly convey our best-use intentions) - we could have a mutually-exclusive `noLabel` boolean prop, requiring either `label` or `noLabel` to be present.
